### ISSUE TITLE
Doesn't work with grunt-contrib-jshint

### ISSUE THREAD

**Issue by efvincent** [spiralx/jshint-summary#2]
Seems that `grunt-contrib-jshint` is looking for the reporter option to be a path to the customer reporter. If you specify the reporter as you show in your read.me:

``` js
grunt.initConfig({
  jshint: {
    options: {
      reporter: require('jshint-summary')
    },
    target: ['file.js']
  }
});
```

grunt will throw an error similar to:

```
C:\...>grunt jshint:all --stack
Running "jshint:all" (jshint) task
Fatal error: Arguments to path.resolve must be strings
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at Object.exports.selectReporter (C:\...\node_modules\grunt-contrib-jshint\tasks\lib\jshint.js:63:33)
```

taking a closer look at `grunt-contrib-jshint` in the `tasks\lib\jshint.js` file, you find this block:

``` js
  // Select a reporter (if not using the default Grunt reporter)
  // Copied from jshint/src/cli/cli.js until that part is exposed
  exports.selectReporter = function(options) {
    switch (true) {

** clipped **

    // Custom reporter
    case options.reporter !== undefined:
      try {
        options.reporter = path.resolve(process.cwd(), options.reporter);
      } catch(err) {
        grunt.fatal(err);
      }
    }
```

Which throws when it hits the `path.resolve(...)` line, because `options.reporter` isn't a string. So is this a bug or am I doing something wrong? Works great with `gulp-jshint` by the way.

**Comment by spiralx** [comment]
I'm going to say it's almost definitely a bug, as I don't use Grunt and so my testing has lapsed since the first version... bad of me, I'll see if I can sort it out later today. It's almost certainly because JSHint doesn't really have a proper API for reporters, so I need a hack for Grunt as well as the hack I put in for Gulp. Shouldn't take long I hope.

Cheers for the report and all the info!

**Comment by spiralx** [comment]
Try changing your `Gruntfile.js` to:

``` js
grunt.initConfig({
  jshint: {
    options: {
      reporter: 'jshint-summary'
    },
    target: ['file.js']
  }
});
```

That should let you run the  reporter, I'll need to have a look at how to define options for it though.

**Comment by efvincent** [comment]
I actually think it's more of a problem with `grunt-contrib-jshint`. It really _should_ work the way you originally illustrated, which makes it easy to pass options. Especially since it used to work that way. I think they've got a regression bug. I'm traveling today but I'll ping them on it tomorrow.

**Comment by spiralx** [comment]
Hmm, I definitely had it working at home - I created my own `Gruntfile.js` and installed Grunt alongside Gulp, and I ran `grunt` with the reporter working as expected. I'll check it when I get in later, what versions of `grunt` and `grunt-contrib-jshint` are you using? I assume it's the latest version of this module :)

**Comment by spiralx** [comment]
I also needed to set `jshintrc` to `'.jshintrc'` in the options for the task before it would run.

**Comment by efvincent** [comment]
I'm using `jshint-summary` 0.3.0, `grunt` version 0.4.5 and `grunt-contrib-jshint` 0.10.0 - latest versions. I still can't get it to work... now wondering if I'm doing something wrong. Here's a gruntfile in a simple project with only the bare essentials:

```
module.exports = function(grunt) {

  grunt.initConfig({
    jshint: {
      options: {
        // this throws:
        reporter: 'jshint-summary',

        // this doesn't throw, but also doesn't do any formatting:
        //reporter: './node_modules/jshint-summary/index.js'

        // As a counter example, this other reporter works
        //reporter: require('jshint-stylish'),

        // This doesn't seem to have an effect
        jshintrc: '.jshintrc'

      },
      all: ['./app/js/**/*.js']
    }

  })

  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.registerTask('default', ['jshint']);
}
```

I tried a couple of different varieties, and I also tried a different reporter, `jshint-stylish`, which works as expected. If you look at the value of `require('jshint-stylish')` it's the full path to the `stylish.js` in the project.

**Comment by spiralx** [comment]
I've resolved the issue, and got it to pick up options from the jshint.options config when using Grunt, but it requires some refactoring so I'm making sure that's all working before I commit, hopefully later today.

**Comment by efvincent** [comment]
That's great! Looking forward to the next drop. Thanks for looking into it...

**Comment by spiralx** [comment]
Cheers :)

**Comment by spiralx** [comment]
Ok, that was more work than expected, partly because since my last update one of the issues that I was working around to get it working in Gulp was fixed, so I can handle both in almost exactly the same way.

I've checked in the update here, is it possible for you to test it by updating your `package.json` so that it uses

``` js
  "jshint-summary": "spiralx/jshint-summary",
```

in the dependencies? You should then be able to do `npm install` and get the code from here.

There's an example `Gruntfile.js` under the `examples` folder now which works here, so hopefully it will work everywhere else :)

**Comment by efvincent** [comment]
The good news is that it does work - the bad news is that it doesn't seem to take the options into account. Similar to the example you supplied, I have in my `gruntfile.js`

```
jshint: {
  options: {
    force: true,
    jshintrc: '.jshintrc',
    reporter: require('jshint-summary'),
    codeCol: 'white',
    reasonCol: 'green,bold',
    statistics: true
 }
}
```

but I still get the default output. If I remove `codeCol`, `reasonCol`, and `statistics`, it looks the same. I'll double check everything on my side.

**Comment by spiralx** [comment]
This is what I get using the default settings i.e. just specifying `reporter` and `jshintrc`:

![jshint-summary-defaults](https://cloud.githubusercontent.com/assets/2296633/3056795/a3e3836e-e1ce-11e3-92df-23d70f2c42c8.png)

And this is what I get when I specify the same options as you have:

![jshint-summary-custom](https://cloud.githubusercontent.com/assets/2296633/3056815/d7d34ae2-e1ce-11e3-8ae1-aff8a9999a6e.png)

How does what you're getting differ?

**Comment by efvincent** [comment]
I get the same results with or without the `jshint-summary` options. Can you create a repo with your sample project?

**Comment by efvincent** [comment]
I can't post my project - it's a client's - I can whip up a test and post to a repo if that's more convenient...

**Comment by spiralx** [comment]
Done:

https://github.com/spiralx/jshint-summary-example

You'll have to edit `package.json` and change the version of `jshint-summary` to point to `spiralx/jshint-summary` again before running `npm install` though.

**Comment by efvincent** [comment]
Your example works perfectly. There must be something about my project that's messed up. I'll continue to look at it and see what it is I'm doing wrong and let you know, lest someone else make the same mistake.

Thanks for taking the time to patch it up. Although I'm tempted to quit trying to fix my client's project and switch to Gulp, which I've been meaning to do for a few weeks...

**Comment by efvincent** [comment]
Got it - I was on a slightly older version of `grunt-contrib-jshint`. My project was originally scaffolded out with yeoman, which built a dependency of `"grunt-contrib-jshint": "~0.7.0"`, and the tilde locked me in at 0.7.*. Switching to a caret allowed npm to pull in 0.10.0, and it started working. 

I realize that you had asked me about the version, but last week when I first registered the issue I was using a different project. So the original problem wasn't about version. This week I was working with a different project and didn't go back and re-check versions - sorry about that.

Thanks again for the good work.

**Comment by spiralx** [comment]
Ah, that's exactly the sort of problem that the new version of `npm` tries to prevent by saving `"grunt-contrib-jshint": "^0.10.0"` now instead of `"grunt-contrib-jshint": "~0.10.0"`. I think it's what the `bundledDependencies` key in `package.json` is for... should have a look, as both Grunt and Gulp require up to date versions.

Glad it was that simple, cheers for the help - I'll make a note about versions in the read me now and then update `npm` with the new version :)

**Comment by spiralx** [comment]
Exciting stuff, version 0.4.0 is now up, you can change your dependencies to `^0.4.0` in your code now :)

https://www.npmjs.org/package/jshint-summary

Closing the ticket - if there are problems, I can reopen. Thanks for your time again :)
